### ISSUE TITLE
扫码成功后地图还卡手上

### ISSUE THREAD

**Issue by PathdarX** [BingZi-233/BilibiliVideo#15]
扫码成功后地图还卡手上，可以再增加一个扫码拿出地图时按Q可以取消的功能

**Comment by BingZi-233** [comment]
请不要使用创造模式进行绑定
创造模式会把虚拟物品转化为实体物品。

**Comment by PathdarX** [comment]
生存就是这样的，地图不会自动取消，得切背包点击才能取消

**Comment by BingZi-233** [comment]
已经调查到问题如何产生的，正在着手处理。
