### ISSUE TITLE
账户状态异常，请过一段时间再次尝试。哔哩哔哩信息:账号异常，操作失败 这个问题只需要等等就好了么

### ISSUE THREAD

**Issue by Unmeldy** [BingZi-233/BilibiliVideo#3]
如上文

**Comment by BingZi-233** [comment]
是的，因为这是B站的风控策略导致的。目前没有什么好的办法解决这个问题，只能等一段时间后尝试。

**Comment by Unmeldy** [comment]
> 是的，因为这是B站的风控策略导致的。目前没有什么好的办法解决这个问题，只能等一段时间后尝试。

等了一晚上 还是这样

**Comment by BingZi-233** [comment]
@Unmeldy 请尝试使用1.0.4看看情况

**Comment by Unmeldy** [comment]
> @Unmeldy 请尝试使用1.0.4看看情况

仍然是账户异常

**Comment by BingZi-233** [comment]
@Unmeldy 登陆看看

**Comment by Unmeldy** [comment]
> @Unmeldy 登陆看看

登陆后去领取的 一直都是 刚刚去测试了还是账户异常

**Comment by Unmeldy** [comment]
> @Unmeldy 登陆看看

可以请你去测试一下嘛 可能会更直观一点

**Comment by BingZi-233** [comment]
很抱歉，白天基本都在工作。基本无法启动游戏进行测试，稍后我会调查这个问题并进行修复。如果修复了会通知你。

**Comment by BingZi-233** [comment]
已查明原因：因为操作了高危API导致的问题。等待进行修复即可。

**Comment by Unmeldy** [comment]
> 已查明原因：因为操作了高危API导致的问题。等待进行修复即可。

实在不行不知能否更改一个稳定点的API

**Comment by BingZi-233** [comment]
我来稍微解释一下，为什么现在出现了账户异常原因。
现在的检测是由插件发起三连，并且检测三连结果。这就导致了在短时间由同一个IP发起了多个账户对某一视频进行操作，估计就是这个原因导致触发了B站风控策略导致临时拉闸。
目前正在修改检测逻辑，更改为检测点赞、投币、收藏这三个是否执行，避免对视频本身进行操作。
这样应该可以绕过B站风控策略，从而让插件正常运行。
但是可能会发起多次请求，不知道会不会再次出触发风控策略。这个之后我会进行测试，等待插件更新吧。

**Comment by BingZi-233** [comment]
如果有能力的话，可以自行修改插件实现目标。

**Comment by BingZi-233** [comment]
该问题已被验证修复，问题关闭。
修复版本：1.0.5-1
