### ISSUE TITLE
指令bilibili-video login 召唤地图扫码 会吞掉手上的物品

### ISSUE THREAD

**Issue by Unmeldy** [BingZi-233/BilibiliVideo#5]

**Comment by BingZi-233** [comment]
地图是虚拟物品，无法覆盖实际背包物品。

**Comment by Unmeldy** [comment]
> 地图是虚拟物品，无法覆盖实际背包物品。 不排除有MOD可以做到虚转实。 另外，创造模式会出现虚转实问题。生存不受影响。

奥奥怪不得 感谢解答 还有另一个issues 麻烦也回答一下从昨晚到现在一直是账户异常
